// src/components/Header.tsx

import React from 'react';
import { motion } from 'framer-motion';

const Header = () => {
  return (
    <motion.header 
      className="w-full py-6 px-6 md:px-8 flex items-center justify-between border-b border-border"
      initial={{ opacity: 0, y: -10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
    >
      <div className="flex items-center space-x-2">
        <motion.div 
          className="h-8 w-8 rounded-full bg-primary"
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
        />
        <motion.h1 
          className="text-xl font-medium tracking-tight"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.1, duration: 0.3 }}
        >
          DocuVue
        </motion.h1>
      </div>
      
      <motion.div 
        className="hidden md:flex items-center space-x-6"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.2, duration: 0.3 }}
      >
        <a 
          href="#" 
          className="text-sm text-foreground/80 hover:text-foreground transition-colors"
        >
          Documentation
        </a>
        <a 
          href="#" 
          className="text-sm text-foreground/80 hover:text-foreground transition-colors"
        >
          Examples
        </a>
        <a 
          href="#" 
          className="text-sm text-foreground/80 hover:text-foreground transition-colors"
        >
          GitHub
        </a>
      </motion.div>
    </motion.header>
  );
};

export default Header;

// src/components/Header.vue

<template>
  <header 
    class="w-full py-6 px-6 md:px-8 flex items-center justify-between border-b border-border"
    v-motion
    :initial="{ opacity: 0, y: -10 }"
    :enter="{ opacity: 1, y: 0 }"
    :transition="{ duration: 400 }">
    
    <div class="flex items-center space-x-2">
      <div class="h-8 w-8 rounded-full bg-primary cursor-pointer"
           v-motion
           :initial="{ scale: 1 }"
           :hover="{ scale: 1.05 }"
           :tap="{ scale: 0.95 }">
      </div>
      <h1 class="text-xl font-medium tracking-tight"
          v-motion
          :initial="{ opacity: 0 }"
          :enter="{ opacity: 1 }"
          :transition="{ delay: 100, duration: 300 }">
        DocuVue
      </h1>
    </div>
    
    <div class="hidden md:flex items-center space-x-6"
         v-motion
         :initial="{ opacity: 0 }"
         :enter="{ opacity: 1 }"
         :transition="{ delay: 200, duration: 300 }">
      <a href="#" class="text-sm text-foreground/80 hover:text-foreground transition-colors">
        Documentation
      </a>
      <a href="#" class="text-sm text-foreground/80 hover:text-foreground transition-colors">
        Examples
      </a>
      <a href="#" class="text-sm text-foreground/80 hover:text-foreground transition-colors">
        GitHub
      </a>
    </div>
  </header>
</template>

<script setup>
import { useMotion } from '@vueuse/motion';
</script>
